#!/bin/bash
#
# Usage: send_speech <filename.flac>
#
# Input file must be .flac, at rate 16000
# Google returns a file is in the form
# {"status":0,"id":"","hypotheses":[{"utterance":"some text here","confidence":0.7664485}]}
# which can be empty:
# {"status":5,"id":"","hypotheses":[]}
# the more, the result file can contain many of such lines! We take the first one only.
 
#FIXME: using $LANG from environment
URL="https://www.google.com/speech-api/v2/recognize?lang=$LANG&client=chromium&key=AIzaSyBOti4mM-6x9WDnZIjIeyEU21OpBXqWBgw"

FILEFOLDER=/tmp/lispeak_$(id -un)
FILE=$FILEFOLDER/result.json

mkdir -p $FILEFOLDER

if [ -z "$1" ];then
    > $FILE
    echo ""
    exit 1
fi

wget -qO- --post-file "$1" --header 'Content-type: audio/x-flac; rate=16000' "$URL" > $FILE

RESULT=$(grep "utterance" $FILE|head -n 1|sed 's/^[^[]*\[{\"utterance\":\"\([^\"]*\)\".*/\1/')

echo $RESULT
